### ISSUE TITLE
`pt_BR` failing with outdated data

### ISSUE THREAD

**Issue by alfsb** [php/doc-base#105]
Hi,

After https://github.com/php/doc-pt_br/commit/e3aa4d793ef2e02b786d16c1af861b2d31b5e41d, the pt_BR manual does not build, with error:
```
The document didn't validate, here are the errors I got:
(If this isn't enough information, try again with --enable-xml-details)
 Element reference content does not follow the DTD, expecting (((title |
 titleabbrev | subtitle)* , info?) , partintro? , refentry+), got (title
 partintro phpdoc:varentry phpdoc:varentry phpdoc:varentry phpdoc:varentry
 phpdoc:varentry phpdoc:varentry phpdoc:varentry phpdoc:varentry phpdoc:varentry
 phpdoc:varentry phpdoc:varentry phpdoc:varentry phpdoc:varentry phpdoc:varentry
```
I cannot find any `varentry` usage outside of DTD definitions. Also, the manual builds locally. I think there is some outdated repository on machine building that is causing this.

I also opened https://github.com/php/doc-base/pull/104 , that may facilitate debug this and future cases. It may be complemented with PHD paths that build machine uses.

**Comment by derickr** [comment]
I think I fixed this now (by making a symlink on `docs.php.net` from the `pt_br` to `pt_BR` directories). It turned out that the rev check tools were not even using the right repositories. I think I fixed that with https://github.com/php/web-doc/commit/e30a3d2392667af8856015890f4e2772270d5670 (`GITDIR` was set-up, but `GIT_DIR` was not).

**Comment by alfsb** [comment]
I confirm that this resolved. Manual is building and updated on www.php.net/manual/.

**Comment by Girgias** [comment]
Thanks for confirming!
